language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - nightly

matrix:
  allow_failures:
    - python: 2.6
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: nightly

sudo: false

before_install:
  - pip install -r requirements.txt -U
  - pip install pytest pytest-mock coverage -U
  - pip install coveralls -U

script:
  - coverage run --source=coop setup.py test

after_success:
  - coveralls